include:
  - docker-compose.infra.yml

services:
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro,z
    depends_on:
      - careerflow-api
      - careerflow-ai
    networks:
      - careerflow-network

  careerflow-api:
    build:
      context: CareerFlow.Core
      dockerfile: src/CareerFlow.Core.Api/Dockerfile
      args:
        - PACKAGE_TOKEN=${PACKAGE_TOKEN}
    container_name: careerflow-api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - PACKAGE_TOKEN=${PACKAGE_TOKEN}
      - Infisical__ClientId=${INFISICAL_CLIENT_ID}
      - Infisical__ClientSecret=${INFISICAL_CLIENT_SECRET}
      - Infisical__ProjectId=${INFISICAL_PROJECT_ID}
      - JwtSettings__Issuer=FreelanceApp
      - JwtSettings__Audience=FreelanceAppUsers
      - PostmarkSettings__FromAddress=contact@carerflow-api.ro
      - PostmarkSettings__FromName=CareerFlow
      - Redis__ConnectionString=redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - careerflow-network

  careerflow-ai:
    build:
      context: CareerFlow.AI
      dockerfile: Dockerfile
    container_name: careerflow-ai
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - careerflow-network

networks:
  careerflow-network:
    driver: bridge