include:
  - docker-compose.infra.yml

services:
  careerflow-api:
    build:
      context: CareerFlow.Core
      dockerfile: src/CareerFlow.Core.Api/Dockerfile
      args:
        - PACKAGE_TOKEN=${PACKAGE_TOKEN}
    container_name: careerflow-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - PACKAGE_TOKEN=${PACKAGE_TOKEN}
      - Infisical__ClientId=${INFISICAL_CLIENT_ID}
      - Infisical__ClientSecret=${INFISICAL_CLIENT_SECRET}
      - Infisical__ProjectId=${INFISICAL_PROJECT_ID}
      - JwtSettings__Issuer=FreelanceApp
      - JwtSettings__Audience=FreelanceAppUsers
      - PostmarkSettings__FromAddress=contact@carerflow-api.ro
      - PostmarkSettings__FromName=CareerFlow
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - careerflow-network